# 1 - Edit the following fields
# 2 - Change file name to config.toml
# 3 - Move config.toml to $HOME/solizard/config.toml
rpc_url = "http://191.29.34.138:8545"
private_key = "395fa17a9c24b21e34e9cf94c5a3a271a651b3a7c83a9abb71c1c0508a45abda"
chain_id = 7700
